language: android
android:
        components:
                - platform-tools
                - build-tools-28.0.3
                - android-28
                - extra-android-m2repository
                - extra-google-google_play_services
                - extra-google-m2repository
                - extra-android-m2repository
                - addon-google_apis-google-28
licenses:
        - 'android-sdk-previewx-license-52d11cd2'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'

script:
        - ./gradlew build
before_install:
        - chmod +x gradlew
branches:
        only:
                - master